### PR TITLE
Tryning Fix 

### PR DESCRIPTION
**Pull request by FehimMahfoud**
I have try fix problem related with dependecy and paramater method

### CODE REVIEW

**Comment by adierkens** [comment]
I'm not quite sure what this PR is trying to fix. If you're having an issue using the library do you mind opening up an issue and we can help debug it?

**Comment by FehimMahfoud** [comment]
Before
Progress
After 
ProgressA

**Comment by FehimMahfoud** [comment]
I have type npm install and when i run the program he give me error by running npm test
For exemple import {Client} from "webdriverio" of the file main.ts of the folder browser/src
so Client do not exist because of that i have try fix and i have think that the problem was that

**Comment by adierkens** [comment]
If you're trying to run this project locally, you'll need to use `yarn` as the project uses yarn workspaces. You'll also need to run `yarn build` in order to build the dependent packages after running `yarn install`

The full command set is: 

```
yarn
yarn build
yarn test
```

**Comment by adierkens** [comment]
@FehimMahfoud if you run into issues running proof in your project, can you please open an issue with the steps to reproduce, and an example repository demonstrating the issue? Then myself or someone else will be happy to help debug and fix it. Thanks for the interest in proof!

**Pull request closed without merging**
